const nodePlugin = require("eslint-plugin-node");

module.exports = [
    {
        ignores: [
            "node_modules/**",
            "logs/**",
            "*.log",
            ".env",
            "cf_keys.txt",
            "errorAccounts.txt",
            "accounts.txt",
        ],
    },
    {
        files: ["**/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "commonjs",
            globals: {
                console: "readonly",
                process: "readonly",
                Buffer: "readonly",
                __dirname: "readonly",
                __filename: "readonly",
                require: "readonly",
                module: "readonly",
                exports: "readonly",
                setTimeout: "readonly",
                setInterval: "readonly",
                clearTimeout: "readonly",
                clearInterval: "readonly",
                Promise: "readonly",
                fetch: "readonly",
            },
        },
        plugins: {
            node: nodePlugin,
        },
        rules: {
            "indent": ["error", 4, { "SwitchCase": 1 }],
            "linebreak-style": ["error", "unix"],
            "quotes": ["error", "double", { "avoidEscape": true }],
            "semi": ["error", "always"],
            "no-unused-vars": ["warn", {
                "argsIgnorePattern": "^_",
                "varsIgnorePattern": "^_",
            }],
            "no-console": "off",
            "comma-dangle": ["error", "always-multiline"],
            "comma-spacing": ["error", { "before": false, "after": true }],
            "key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
            "keyword-spacing": ["error", { "before": true, "after": true }],
            "space-before-blocks": ["error", "always"],
            "space-before-function-paren": ["error", {
                "anonymous": "always",
                "named": "never",
                "asyncArrow": "always",
            }],
            "space-in-parens": ["error", "never"],
            "space-infix-ops": "error",
            "arrow-spacing": ["error", { "before": true, "after": true }],
            "object-curly-spacing": ["error", "always"],
            "array-bracket-spacing": ["error", "never"],
            "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
            "eqeqeq": ["error", "always", { "null": "ignore" }],
            "no-trailing-spaces": "error",
            "no-multiple-empty-lines": ["error", { "max": 1, "maxEOF": 0 }],
            "eol-last": ["error", "always"],
            "prefer-const": "warn",
            "no-var": "error",
            "prefer-arrow-callback": "warn",
            "prefer-template": "warn",
            "template-curly-spacing": ["error", "never"],
            "arrow-parens": ["error", "always"],
            "no-useless-concat": "error",
            "no-multi-spaces": "error",
            "no-constant-condition": ["error", { "checkLoops": false }],
            "no-undef": "error",
            "no-redeclare": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-empty": "warn",
            "no-unreachable": "error",
            "valid-typeof": "error",
            "curly": ["error", "all"],
            "dot-notation": "warn",
            "no-eval": "error",
            "no-implied-eval": "error",
            "no-return-await": "warn",
            "require-await": "warn",
        },
    },
];
